name: Salesforce CI/CD Validation

on:
  pull_request:
    branches: [ OrgSource ]

jobs:
  # --- PMD Static Analysis ---
  pmd:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Run PMD
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'config/ruleset.xml'
          sourcePath: 'force-app/main/default'
          version: latest
          analyzeModifiedFilesOnly: true
          createGitHubAnnotations: true
          uploadSarifReport: false